# Find OPENCV
#
# OPENCV_INCLUDE_DIRS
# OPENCV_LIBRARIES
# OPENCV_FOUND
#
# OPENCV_${COMPONENT}_INCLUDE_DIR
# OPENCV_${COMPONENT}_LIBRARY
#

SET(OPENCV_COMPONENTS
	calib3d
        contrib
	core
	features2d
	flann
        gpu
	highgui
	imgproc
        legacy
	ml
	objdetect
	ts
	#video
        videoio
        imgcodecs
)

FOREACH(COMPONENT ${OPENCV_COMPONENTS})
	STRING(TOLOWER ${COMPONENT} LOWERCOMPONENT)
	STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

	FIND_PATH(OPENCV_${UPPERCOMPONENT}_INCLUDE_DIR NAMES opencv/cv.h)

	FIND_LIBRARY(OPENCV_${UPPERCOMPONENT}_LIBRARY NAMES opencv_${LOWERCOMPONENT})

	SET(${OPENCV_${UPPERCOMPONENT}_FOUND} 1)

	MARK_AS_ADVANCED(OPENCV_${UPPERCOMPONENT}_INCLUDE_DIR OPENCV_${UPPERCOMPONENT}_LIBRARY OPENCV_${UPPERCOMPONENT}_FOUND)
ENDFOREACH(COMPONENT)

IF(NOT OPENCV_FIND_COMPONENTS)
	SET(OPENCV_FIND_COMPONENTS ${OPENCV_COMPONENTS})
ENDIF(NOT OPENCV_FIND_COMPONENTS)

SET(OPENCV_FOUND "YES")
FOREACH(COMPONENT ${OPENCV_FIND_COMPONENTS})
	STRING(TOLOWER ${COMPONENT} LOWERCOMPONENT)
	STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


	IF(OPENCV_${UPPERCOMPONENT}_LIBRARY AND OPENCV_${UPPERCOMPONENT}_INCLUDE_DIR)
		LIST(APPEND OPENCV_LIBRARIES ${OPENCV_${UPPERCOMPONENT}_LIBRARY})
		LIST(APPEND OPENCV_INCLUDE_DIRS ${OPENCV_${UPPERCOMPONENT}_INCLUDE_DIR})
		MESSAGE(STATUS "found lib${LOWERCOMPONENT}: -I${OPENCV_${UPPERCOMPONENT}_INCLUDE_DIR}, ${OPENCV_${UPPERCOMPONENT}_LIBRARY}")
	ELSE(OPENCV_${UPPERCOMPONENT}_LIBRARY AND OPENCV_${UPPERCOMPONENT}_INCLUDE_DIR)
		SET(OPENCV_FOUND "NO")
		IF(OPENCV_FIND_REQUIRED)
			MESSAGE(FATAL_ERROR "Required opencv component ${LOWERCOMPONENT} NOT found")
		ELSE(OPENCV_FIND_REQUIRED)
			MESSAGE(STATUS "opencv component ${LOWERCOMPONENT} NOT found")
		ENDIF(OPENCV_FIND_REQUIRED)
	ENDIF(OPENCV_${UPPERCOMPONENT}_LIBRARY AND OPENCV_${UPPERCOMPONENT}_INCLUDE_DIR)
ENDFOREACH(COMPONENT)

IF(OPENCV_INCLUDE_DIRS)
	LIST(REMOVE_DUPLICATES OPENCV_INCLUDE_DIRS)
ENDIF(OPENCV_INCLUDE_DIRS)

MARK_AS_ADVANCED(OPENCV_LIBRARIES OPENCV_INCLUDE_DIRS OPENCV_FOUND)
