module Jeera.Abs where

-- Haskell module generated by the BNF converter


newtype IDENT = IDENT String deriving (Eq,Ord,Show)
data Design =
   Design [DeviceDecl]
  deriving (Eq,Ord,Show)

data DeviceDecl =
   DeviceDecl DeviceType [Assignment]
  deriving (Eq,Ord,Show)

data DeviceType =
   DeviceType_Registor
 | DeviceType_Capacitor
 | DeviceType_Inductance
 | DeviceType_Voltage
  deriving (Eq,Ord,Show)

data Assignment =
   Assignment IDENT IDENT
  deriving (Eq,Ord,Show)

