all:
	happy -gca jeera/Par.y
	alex -g jeera/Lex.x
	(cd jeera/; latex Doc.tex; dvips Doc.dvi -o Doc.ps)
	ghc --make jeera/Test.hs -o jeera/Test
clean:
	-rm -f jeera/*.log jeera/*.aux jeera/*.hi jeera/*.o jeera/*.dvi
	-rm -f jeera/Doc.ps
distclean: clean
	-rm -f jeera/Doc.* jeera/Lex.* jeera/Par.* jeera/Layout.* jeera/Skel.* jeera/Print.* jeera/Test.* jeera/Abs.* jeera/Test jeera/ErrM.* jeera/SharedString.* jeera/jeera.dtd jeera/XML.* Makefile*
	-rmdir -p jeera/
