FROM opensuse/leap:15.2
MAINTAINER Dilawar Singh <dilawar.s.rajput@gmail.com>
RUN zypper -n ar -f -G https://download.opensuse.org/repositories/OBS:/Server:/2.10/openSUSE_15.2/OBS:Server:2.10.repo
RUN zypper in -n -y -t pattern OBS_Server 
